/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package ui.Hospital;
//package ui.NgoRole;

import ui.MhaRole.*;
import ui.AdministrativeRole.*;
import bbank.Bbank;
import bbank.Donor.DeliveryManDirectory;
import ui.Hospital.HospitalWorkAreaJPanel;
import ui.NgoRole.PatientsJPanel;
import ui.NgoRole.AvailableJPanel;
import ui.NgoRole.BloodbanksJPanel;
import ui.NgoRole.ViewdonorsJPanel;

import bbank.UserAccount.UserAccount;
import bbank.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author  akhil
 */
public class HospitalWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Bbank business;
    
    /** Creates new form AdminWorkAreaJPanel */
     private JPanel workArea;
    
    private bbank.Donor.DeliveryMan dorganization;
    private bbank.Donor.DeliveryManDirectory ddirectory;
       private UserAccount userAccount;
    private UserAccount userAccount1;
    private UserAccountDirectory Daccount;
    private DeliveryManDirectory dmanlist;
    String user,roletype;
    public HospitalWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,String user, String roletype) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
          this.workArea = workArea;
      this.user=user;
      this.roletype=roletype;
        this.business = business;
        this.userAccount = account;
        
       //  this.userAccount1 = account1;
         // String foodname="/food1.jpg";
        // ImageIcon icon=createImageIcon(foodname,"x"); 
                               //   icon.getImage().flush();
                                //  icon = createImageIcon(foodname, "a");
       // userProcessContainer.imageUpdate(foodname, SOMEBITS, WIDTH, WIDTH, WIDTH, WIDTH);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbank = new javax.swing.JButton();
        btnpatient = new javax.swing.JButton();
        btnavailable = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btndonor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(424, 344));

        btnbank.setBackground(new java.awt.Color(102, 153, 255));
        btnbank.setText("Blood Banks");
        btnbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbankActionPerformed(evt);
            }
        });

        btnpatient.setBackground(new java.awt.Color(102, 153, 255));
        btnpatient.setText("Patient Request");
        btnpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientActionPerformed(evt);
            }
        });

        btnavailable.setBackground(new java.awt.Color(102, 153, 255));
        btnavailable.setText("Check Blood Availability");
        btnavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnavailableActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Hospital Work Area");

        btndonor.setBackground(new java.awt.Color(102, 153, 255));
        btndonor.setText("Donors List");
        btndonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonorActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Annapurna\\Documents\\NetBeansProjects\\blood-bank\\hospital.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnbank, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(btndonor, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addComponent(btnpatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnavailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnavailable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndonor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbank))
                    .addComponent(jLabel1))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientActionPerformed

      PatientsJPanel  patientsJPanel = new  PatientsJPanel(userProcessContainer);
        userProcessContainer.add("manageBloodJPanel",  patientsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
        
    }//GEN-LAST:event_btnpatientActionPerformed

    private void btnavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavailableActionPerformed

        AvailableJPanel availableJPanel = new AvailableJPanel(userProcessContainer);
        userProcessContainer.add("manageBloodJPanel", availableJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnavailableActionPerformed

    private void btndonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonorActionPerformed
        // TODO add your handling code here:
          ViewdonorsJPanel viewdonorsJPanel = new ViewdonorsJPanel(userProcessContainer);
        userProcessContainer.add("View DonorsJPanel", viewdonorsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btndonorActionPerformed

    private void btnbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbankActionPerformed
        // TODO add your handling code here:
        BloodbanksJPanel bloodbanks = new BloodbanksJPanel(userProcessContainer);
        userProcessContainer.add("Bloodbanks", bloodbanks);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnbankActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnavailable;
    private javax.swing.JButton btnbank;
    private javax.swing.JButton btndonor;
    private javax.swing.JButton btnpatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
  
    protected ImageIcon createImageIcon(String path,
                                           String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
         System.err.println("found file: " + path+" url "+imgURL);
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path+" url "+imgURL);
        return null;
    }
}
}
