/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


//import business.DB4OUtil.DB4OUtil;
import bbank.Bbank;
import bbank.ConfigureABusiness;
//import business.DB4OUtil.DB4OUtil;

//import Bbank.DB4OUtil.DB4OUtil;





import java.awt.CardLayout;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Bbank system;
     private Bbank systemnew;
   

    public MainJFrame() {
        initComponents();
          system = ConfigureABusiness.configure();
           systemnew = ConfigureABusiness.configure(); 
                   System.out.println("system="+system);
               //   System.out.println("systemdata =" +system.getDeliveryDirectory().getDeliveryMan());
        // systemnew = dB4OUtil.retrieveSystem(Bbank.class);
         System.out.println("system mainframe db="+system);
            System.out.println("system new in mainframe  =" +systemnew);
         this.setSize(1680, 1050);
   // this.setSize(680, 650);
                initLoginScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainWorkArea.setBackground(new java.awt.Color(255, 255, 255));
        mainWorkArea.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainWorkArea, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainWorkArea;
    // End of variables declaration//GEN-END:variables

    private void initLoginScreen() {

        JPanel loginScreen = new LoginScreen(mainWorkArea,systemnew);
        mainWorkArea.add("LoginScreen", loginScreen);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
         System.out.println("calling stored from mainframe");
          System.out.println("system in login="+system);
            System.out.println("system new in login =" +systemnew);
       // dB4OUtil.storeSystem(system);

    }
}
