/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bbank.DB.DButil;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author akhil
 */

public class NgoregJPanel1 extends JPanel {
   // Restaurant restaurant;
         private JPanel userProcessContainer;
    int did=0;
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public NgoregJPanel1(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
          ResultSet resultSet = null;
           DButil dbconn= new DButil();
          Connection conn = dbconn.getConnection();
                        
       
    }
    
    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        btnreg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuserid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpasswd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 255));
        setDoubleBuffered(false);
        setMaximumSize(new java.awt.Dimension(367, 367));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(102, 153, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, -1, -1));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Register as NGO");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 44, -1, -1));

        jLabel1.setText("NGO Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 74, -1));

        jLabel2.setText("Address");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 74, -1));

        btnreg.setBackground(new java.awt.Color(102, 153, 255));
        btnreg.setText("Register");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });
        add(btnreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 306, 87, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/akhil_kaundinya/AED_final_P/github/BloodBankAEDFinalProject/ngo.png")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 102, 210, 230));

        jLabel4.setText("Userid");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        add(txtuserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 74, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));
        add(txtpasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 74, -1));

        jLabel7.setText("Mobile");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));
        add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 74, -1));

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
        // TODO add your 
       // int donorid=Integer.parseInt(txtid.getText());
        int mobile=0;
          ResultSet resultSet = null;
       String address=txtaddress.getText();
        String ngoname=txtname.getText();
        String userid=txtuserid.getText();
        
        String pass=txtpasswd.getText();
        mobile=Integer.parseInt(txtmobile.getText());
        //
    int stop=0;
     if(txtname.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid name");
         stop=1;
     }
     if(txtaddress.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid address");
         stop=1;
     }
  
    
    
     if(txtuserid.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid ID");
         stop=1;
     }
      int did=0;
    
     
   //
  
         DButil dbconn= new DButil();
          Connection conn = dbconn.getConnection();
          
          //find if userid already there
            String checkSql = "SELECT * from users";
      Statement stmtc;
       try {
            stmtc = conn.createStatement();
       
            resultSet = stmtc.executeQuery(checkSql);
              
            // conn.close();
             while (resultSet.next()) {
                 // did=resultSet.getInt(1);
              //    System.out.println("1="+resultSet.getString(1)+" userid"+userid+"2="+resultSet.getString(2)+" pass"+pass);
                   if((resultSet.getString(1).equals(userid))||(resultSet.getString(2).equals(pass)))
                   { //System.out.print("inside");
                        JOptionPane.showMessageDialog(this, "UserID/Password already exists");
                  return;
                   }
                       }//while
             did++;
             System.out.print("did "+did);
           //  conn.close();
            
       }//try
       catch (SQLException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
                
       
          //find if useid already there
           // Connection conn = DriverManager.getConnection(dburl, user, pass);
 System.out.println("Connected to database !");
 // String selectSql = "insert into Doners values("+did+","+donorname+","+address+","+bgroup+",9999999999,0,0)";
 String selectSql = "insert into ngo(name,address,mobile,status)" +" values(?,?,?,?);";
 String  selectSql1 = "insert into users(user_id,passwd,role_id,username,status)" +" values(?,?,?,?,?);";
 PreparedStatement stmt,stmt1;
       
          try {
             // stmt = conn.createStatement();
             stmt=conn.prepareStatement(selectSql);
              stmt1=conn.prepareStatement(selectSql1);
          
             stmt.setString(1, ngoname);
              stmt.setString(2, address);
              stmt.setInt(3, mobile);
                 stmt.setInt(4, 0);
                                 
              stmt.executeUpdate();
              stmt1.setString(1, userid);
               stmt1.setString(2, pass);
               
                stmt1.setInt(3, 5);
                 stmt1.setString(4, ngoname);
                 stmt1.setInt(5, 0);
                  stmt1.executeUpdate();
                  conn.close();
          } catch (SQLException ex) {
              Logger.getLogger(NgoregJPanel1.class.getName()).log(Level.SEVERE, null, ex);
          }
   
  
  
  
JOptionPane.showMessageDialog(this,"new NGO added");

     
  //stop

  txtname.setText("");
   txtaddress.setText("");
    
       
    }//GEN-LAST:event_btnregActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnreg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpasswd;
    private javax.swing.JTextField txtuserid;
    // End of variables declaration//GEN-END:variables

}
