/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package ui.AdministrativeRole;

import bbank.Bbank;
import bbank.Donor.DeliveryManDirectory;


import bbank.UserAccount.UserAccount;
import bbank.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author  akhil
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Bbank business;
    
    /** Creates new form AdminWorkAreaJPanel */
     private JPanel workArea;
    
    private bbank.Donor.DeliveryMan dorganization;
    private bbank.Donor.DeliveryManDirectory ddirectory;
       private UserAccount userAccount;
    private UserAccount userAccount1;
    private UserAccountDirectory Daccount;
    private DeliveryManDirectory dmanlist;
    String user,roletype;
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,String user,String roletype) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
          this.workArea = workArea;
      
        this.business = business;
        this.userAccount = account;
        this.user=user;
        this.roletype=roletype;
        System.out.println("user  "+user+ " roletype  "+roletype);
       //  this.userAccount1 = account1;
         // String foodname="/food1.jpg";
        // ImageIcon icon=createImageIcon(foodname,"x"); 
                               //   icon.getImage().flush();
                                //  icon = createImageIcon(foodname, "a");
       // userProcessContainer.imageUpdate(foodname, SOMEBITS, WIDTH, WIDTH, WIDTH, WIDTH);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userJButton = new javax.swing.JButton();
        btnbbank = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnreceive = new javax.swing.JButton();
        btnstock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnhos = new javax.swing.JButton();

        setBackground(new java.awt.Color(221, 230, 227));
        setPreferredSize(new java.awt.Dimension(424, 344));

        userJButton.setBackground(new java.awt.Color(212, 49, 50));
        userJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        userJButton.setForeground(new java.awt.Color(255, 255, 255));
        userJButton.setText("Manage Users");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });

        btnbbank.setBackground(new java.awt.Color(212, 49, 50));
        btnbbank.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnbbank.setForeground(new java.awt.Color(255, 255, 255));
        btnbbank.setText("Blood Banks");
        btnbbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbbankActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Administrative Work Area");

        btnreceive.setBackground(new java.awt.Color(212, 49, 50));
        btnreceive.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnreceive.setForeground(new java.awt.Color(255, 255, 255));
        btnreceive.setText("Employees");
        btnreceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreceiveActionPerformed(evt);
            }
        });

        btnstock.setBackground(new java.awt.Color(212, 49, 50));
        btnstock.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnstock.setForeground(new java.awt.Color(255, 255, 255));
        btnstock.setText("Analyse Stock");
        btnstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstockActionPerformed(evt);
            }
        });

        btnhos.setBackground(new java.awt.Color(212, 49, 50));
        btnhos.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnhos.setForeground(new java.awt.Color(255, 255, 255));
        btnhos.setText("Hospitals");
        btnhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnbbank)
                        .addGap(43, 43, 43)
                        .addComponent(btnhos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnreceive, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(userJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnstock, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnbbank, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreceive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstock, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer,roletype);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void btnbbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbbankActionPerformed

        ManageBloodJPanel manageBloodJPanel = new ManageBloodJPanel(userProcessContainer);
        userProcessContainer.add("manageBloodJPanel", manageBloodJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnbbankActionPerformed

    private void btnreceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreceiveActionPerformed
        // TODO add your handling code here:
          ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer,user,roletype);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnreceiveActionPerformed

    private void btnstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstockActionPerformed
        // TODO add your handling code here:
    ViewstockJPanel  viewstock = new  ViewstockJPanel( userProcessContainer, user,roletype);    
    userProcessContainer.add(" Viewstock",  viewstock);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnstockActionPerformed

    private void btnhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhosActionPerformed
        // TODO add your handling code here:
         ManagehospitalJPanel  managehospital = new  ManagehospitalJPanel( userProcessContainer);    
    userProcessContainer.add(" Managehospital",  managehospital);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnhosActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbbank;
    private javax.swing.JButton btnhos;
    private javax.swing.JButton btnreceive;
    private javax.swing.JButton btnstock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables
  
    protected ImageIcon createImageIcon(String path,
                                           String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
         System.err.println("found file: " + path+" url "+imgURL);
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path+" url "+imgURL);
        return null;
    }
}
}
